name: "Explore OpenAPI Snapshot"
description: "Create a snapshot of OpenAPI schema at https://explore-openapi.dev"
author: "patzick"

inputs:
  schema-file:
    description: "Path to the JSON schema file"
    required: true
  project:
    description: "Project name or project ID"
    required: true
  snapshot-name:
    description: "Snapshot name (defaults to PR number if in PR context, otherwise branch name)"
    required: false
  auth-token:
    description: "Authentication token for API (legacy method, use OIDC instead)"
    required: false
  github-token:
    description: "GitHub token (deprecated - PR comments are now posted by backend GitHub App)"
    required: false
    default: ${{ github.token }}
  permanent:
    description: "Whether to create a permanent snapshot (defaults to true for branch/tag pushes, false for PRs)"
    required: false
  use-oidc:
    description: "Use OIDC token for authentication (recommended, works with forks)"
    required: false
    default: "false"
  oidc-audience:
    description: "OIDC token audience (only used when use-oidc is true)"
    required: false
    default: "https://explore-openapi.dev"

outputs:
  snapshot-url:
    description: "URL to the created snapshot"
  response:
    description: "Full API response"

runs:
  using: "node24"
  main: "dist/index.js"

branding:
  icon: "file-text"
  color: "blue"
