name: 'OpenAPI Snapshot'
description: 'Create a snapshot of OpenAPI schema at explore-openapi.dev'
author: 'patzick'

inputs:
  schema-file:
    description: 'Path to the JSON schema file'
    required: true
  api-url:
    description: 'API endpoint URL to send the schema to'
    required: true
    default: 'https://explore-openapi.dev/api/snapshot'
  auth-token:
    description: 'Authentication token for API'
    required: true
  github-token:
    description: 'GitHub token for commenting on PR'
    required: true
    default: ${{ github.token }}

outputs:
  snapshot-url:
    description: 'URL to the created snapshot'
  response:
    description: 'Full API response'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'file-text'
  color: 'blue'
