name: Test OpenAPI Snapshot Action (OIDC)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC authentication

jobs:
  test-action-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run OpenAPI Snapshot Action (OIDC)
        uses: ./
        with:
          schema-file: "./example-schema.json"
          project: "test-project-oidc"
          use-oidc: "true"
